---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-route-curl-client
  labels:
    app: tcp-route-curl-client
spec:
  containers:
    - name: sidecar-demo-00
      image: lukelau/curl:0.0.1
      command: ['sh', '-c', 'sleep 100000']
