apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: http-echo-server
    version: v1
  name: http-echo-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-echo-server
      version: v1
  template:
    metadata:
      labels:
        app: http-echo-server
        version: v1
    spec:
      containers:
        - image: lukelau/echo:0.0.1
          imagePullPolicy: IfNotPresent
          name: http-echo-server
          args:
            - '-server.addr'
            - '0.0.0.0:8080'
          env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
