# Source: https://liqinag.io
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-prometheus-node-exporter
  labels:
    app: prometheus-node-exporter
    heritage: Tiller
    release: release-name
    chart: prometheus-node-exporter-1.7.2
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: release-name
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: prometheus-node-exporter
        heritage: Tiller
        release: release-name
        chart: prometheus-node-exporter-1.7.2
    spec:
      serviceAccountName: release-name-prometheus-node-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534

      containers:
        - name: node-exporter
          image: "quay.io/prometheus/node-exporter:v0.18.0"
          imagePullPolicy: IfNotPresent
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --web.listen-address=0.0.0.0:9100
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9100
          readinessProbe:
            httpGet:
              path: /
              port: 9100
          resources:
            {}

          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      tolerations:
        - effect: NoSchedule
          operator: Exists

      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
