apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grpc-demo-server
  labels:
    app: grpc-demo-server
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: grpc-demo-server
  template:
    metadata:
      labels:
        app: grpc-demo-server
    spec:
      containers:
        - name: grpc-demo-server
          image: lukelau/grpc-server:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-demo-server
spec:
  selector:
    app: grpc-demo-server
  ports:
    - port: 9321
      targetPort: 9321
  type: LoadBalancer
