---
apiVersion: v1
kind: Pod
metadata:
  name: no-inject-pods
  labels:
    app: no-inject-pods
spec:
  containers:
    - name: grpc-client
      image: lukelau/grpc-client:1.1
      command: ['sh', '-c', 'sleep 100000']
