---
apiVersion: v1
kind: Pod
metadata:
  name: injected-pods
  labels:
    app: injected-pods
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  containers:
    - name: grpc-client
      image: lukelau/grpc-client:1.1
      command: ['sh', '-c', 'sleep 100000']
