---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: liqiang-io
spec:
  hosts:
    - liqiang.io
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: liqiang.io
            port:
              number: 443
