---
kind: Service
apiVersion: v1
metadata:
  name: istio
  namespace: istio-system
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: istio-egressgateway
    istio: egressgateway
    release: istio

