// Code generated by protoc-gen-go. DO NOT EDIT.
// source: 00.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_00_04b8672eec995032, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Response struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00_04b8672eec995032, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "post06.Request")
	proto.RegisterType((*Response)(nil), "post06.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Post06Client is the client API for Post06 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type Post06Client interface {
	Sum(ctx context.Context, opts ...grpc.CallOption) (Post06_SumClient, error)
}

type post06Client struct {
	cc *grpc.ClientConn
}

func NewPost06Client(cc *grpc.ClientConn) Post06Client {
	return &post06Client{cc}
}

func (c *post06Client) Sum(ctx context.Context, opts ...grpc.CallOption) (Post06_SumClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Post06_serviceDesc.Streams[0], "/post06.Post06/Sum", opts...)
	if err != nil {
		return nil, err
	}
	x := &post06SumClient{stream}
	return x, nil
}

type Post06_SumClient interface {
	Send(*Request) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type post06SumClient struct {
	grpc.ClientStream
}

func (x *post06SumClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *post06SumClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Post06Server is the server API for Post06 service.
type Post06Server interface {
	Sum(Post06_SumServer) error
}

func RegisterPost06Server(s *grpc.Server, srv Post06Server) {
	s.RegisterService(&_Post06_serviceDesc, srv)
}

func _Post06_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(Post06Server).Sum(&post06SumServer{stream})
}

type Post06_SumServer interface {
	SendAndClose(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type post06SumServer struct {
	grpc.ServerStream
}

func (x *post06SumServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *post06SumServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Post06_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post06.Post06",
	HandlerType: (*Post06Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sum",
			Handler:       _Post06_Sum_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "00.proto",
}

func init() { proto.RegisterFile("00.proto", fileDescriptor_00_04b8672eec995032) }

var fileDescriptor_00_04b8672eec995032 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x30, 0x30, 0xd0, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xc8, 0x2f, 0x2e, 0x31, 0x30, 0x53, 0x92, 0xe6, 0x62,
	0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe0, 0x62, 0xce, 0x2b, 0xcd, 0x95, 0x60,
	0x54, 0x60, 0xd4, 0x60, 0x0e, 0x02, 0x31, 0x95, 0x94, 0xb8, 0x38, 0x82, 0x52, 0x8b, 0x0b, 0xf2,
	0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xa0, 0x0a, 0xa0,
	0x3c, 0x23, 0x33, 0x2e, 0xb6, 0x00, 0xb0, 0x51, 0x42, 0x3a, 0x5c, 0xcc, 0xc1, 0xa5, 0xb9, 0x42,
	0xfc, 0x7a, 0x10, 0xa3, 0xf5, 0xa0, 0xe6, 0x4a, 0x09, 0x20, 0x04, 0x20, 0x66, 0x29, 0x31, 0x68,
	0x30, 0x3a, 0x71, 0x45, 0x71, 0x80, 0x5d, 0x92, 0x54, 0x9a, 0x96, 0xc4, 0x06, 0x66, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x50, 0x47, 0xd1, 0x9f, 0x00, 0x00, 0x00,
}
